### ISSUE TITLE
Add a github action to create a kind cluster and run some tests

### ISSUE THREAD

**Issue by dims** [dims/hydrophone#16]
- Run a single test (quick!)
- Run conformance tests.

**Comment by rjsadow** [comment]
@dims for `Run conformance tests.` what are you envisioning? Running the entire conformance suite?

**Comment by dims** [comment]
@rjsadow not on every PR, but periodically

**Comment by dims** [comment]
using `--focus='[conformance]'`

**Comment by rjsadow** [comment]
Periodic test is running (https://github.com/dims/hydrophone/actions/runs/7284630106), however it does exit with a successful return code. I'm gathering that hydrophone is running the test, reporting on the logs of the pod, then exits successfully. This will make any CI tests difficult to determine if there are failures. @dims how do you feel about tying the exit code of hydrophone with the exit code of the pod?

**Comment by dims** [comment]
sounds good @rjsadow

**Comment by rjsadow** [comment]
#28 didn't work as expected. I'll look into more how we can ensure we bubble up the test status

https://github.com/dims/hydrophone/actions/runs/7287900898/job/19859462277#step:8:37974

**Comment by dims** [comment]
let's open up fresh issues as we see these @rjsadow - i have some changes in there which should help.
